apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: reactjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: ankit21sh/ankit:nodejs
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-app
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 31000